### ISSUE TITLE
Deprecate this on npm

### ISSUE THREAD

**Issue by callumlocke** [andris9/highlight#14]
The page on NPM doesn't say it's deprecated: https://www.npmjs.com/package/highlight

It would be good to publish another version of this so the NPM page gets the latest version of the readme, with the big deprecation warning.

**Comment by andris9** [comment]
Bumped version and pushed updated README to npm. Also added deprecation notice to npm install:

```
$ npm install highlight
npm WARN deprecated highlight@0.2.4: Not maintained anymore
highlight@0.2.4 node_modules/highlight
```
